#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the viralAdvertising function below.
def viralAdvertising(n):
    cumulative=2
    like_today= (5//2)
    spread= like_today*3
    for i in range (2,n+1):
        like_today=(spread//2)
        spread=like_today*3
        cumulative+=like_today

    return cumulative

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()
